version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./logs:/app/logs
    environment:
      - MAVEN_HOME=/usr/local/maven
      - PATH=$MAVEN_HOME/bin:$PATH
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
